In [11]:
import cv2
import numpy as np

In [12]:
newImgInfo=(600,500,3)

In [13]:
dst=np.zeros((newImgInfo),np.uint8)

In [14]:
#               左上角坐标点  右下角坐标点
dst=cv2.rectangle(dst,(200,200),   (60,60),(0,0,255),2)
#red-颜色
#2-线条宽度
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)

In [5]:
cv2.rectangle(dst,(50,200),   (220,280),(255,0,0),-1)
#-1 表示填充
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)

In [6]:

cv2.circle(dst,(250,250),(50),(0,255,0),5)
cv2.circle(dst,(250,250),(10),(0,0,255),5)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)

In [7]:
#椭圆， 1 dst 2圆心 3 轴（第一个数表示水平的半轴长度，第二个数表示竖直方向的半轴长度）
#       4 angle计算的起始点（顺时针方向） 5 相当于起始点的begin angle（顺时针方向） 6 相对于起始点的end angle
#       7 color 8 是否填充 -1表示填充正数表示线宽
cv2.ellipse(dst,(300,300),(150,100),90,90,360,(255,255,0),-1)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)

In [8]:
dst=np.zeros((300,300,3),dtype='uint8')
(cx,cy)=dst.shape[1]//2,dst.shape[0]//2
white=(255,255,255)
for r in range(0,151,15):
    cv2.circle(dst,(cx,cy),r,white,2)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)
# (cx,cy) - 圆心
# r - 半径
# white - 颜色
# 2 - 线宽度

In [9]:
image=np.zeros((300,300,3),dtype='uint8')
for i in range(10):
    #半径取值
    radius=np.random.randint(5,200)
    #颜色取值
    color=np.random.randint(0,255,size=(3,)).tolist()
    #圆心取值
    pt=np.random.randint(0,300,size=(2,))
    #画图
    cv2.circle(image,tuple(pt),radius,color,-1)
cv2.imshow('dst2',image)
cv2.waitKey(0)
cv2.destroyAllWindows()
dst=np.zeros((newImgInfo),np.uint8)

In [10]:
dst=np.zeros((600,500,3),np.uint8)
cv2.line(dst,(100,100),(100,300),(0,0,255),20,cv2.LINE_AA)
cv2.line(dst,(100,300),(400,300),(255,0,255),20,cv2.LINE_AA)
cv2.line(dst,(400,300),(400,100),(0,255,0),20,cv2.LINE_AA)
cv2.line(dst,(400,100),(100,100),(0,255,0),20,cv2.LINE_AA)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
dst=np.zeros((600,500,3),np.uint8)
#闭合的任意多边形 注意要首尾相连
points=np.array([[150,50],[140,150],[130,120],[100,90]],np.int32)
print(points.shape)
print(points)
points=points.reshape(-1,1,2)#矩阵转换，把5*2的矩阵转置为5*1*2 ，-1表示不设置具体的值，其值由另外两个参数计算得到。
print(points.shape)
print(points)
#True&Flase 是否闭合折现，True闭合，Flase不闭合
cv2.polylines(dst,[points],True,(255.255,0),5)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(4, 2)
[[150  50]
 [140 150]
 [130 120]
 [100  90]]
(4, 1, 2)
[[[150  50]]

 [[140 150]]

 [[130 120]]

 [[100  90]]]


In [23]:
dst=np.zeros((600,500,3),np.uint8)
#闭合的任意多边形 注意要首尾相连
points=np.array([[150,50],[140,150],[130,120],[100,90]],np.int32)
print(points.shape)
print(points)
points=points.reshape(-1,1,2)#矩阵转换，把5*2的矩阵转置为5*1*2 ，-1表示不设置具体的值，其值由另外两个参数计算得到。
print(points.shape)
print(points)
#True&False 是否闭合折现，True闭合，False不闭合
cv2.polylines(dst,[points],False,(255.255,0),5)
cv2.imshow('dst2',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(4, 2)
[[150  50]
 [140 150]
 [130 120]
 [100  90]]
(4, 1, 2)
[[[150  50]]

 [[140 150]]

 [[130 120]]

 [[100  90]]]
