In [ ]:
#cv2.threshold() 进行函数的阈值化处理

In [27]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 二值化阈值处理

In [28]:
# img=cv2.imread('image1.jpg',1)
img=np.random.randint(0,256,size=(4,5),dtype=np.uint8)
t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
print('img=\n',img)
print('t=',t)
print('rst=\n',rst)

img=
 [[  0 205  15  57 244]
 [191 164  73 172 109]
 [218 194  48 236 242]
 [123  97 196  48 178]]
t= 127.0
rst=
 [[  0 255   0   0 255]
 [255 255   0 255   0]
 [255 255   0 255 255]
 [  0   0 255   0 255]]


In [41]:
#二值化阈值处理
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
r,dst=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
# print(dst.shape)
# print(type(dst))
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
# img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)#BGR转换为RGB位图
# plt.imshow(dst)
# plt.axis('off')#去掉坐标
# plt.show()
# plt.imshow(img)
# plt.axis('off')#去掉坐标
# plt.show()

In [42]:
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
thresh=127
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        px=img[i,j]
        if px< thresh :
            dst[i,j]=0
        else:
            dst[i,j]=255
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 反二值化阈值处理

In [17]:
img=np.random.randint(0,256,size=(4,5),dtype=np.uint8)
t,rst=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
print('img=\n',img)
print('t=',t)
print('rst=\n',rst)

img=
 [[ 22  81 252  60  36]
 [ 45  98 128  11  22]
 [157 127 110  33 139]
 [149 125  49   0 206]]
t= 127.0
rst=
 [[255 255   0 255 255]
 [255 255   0 255 255]
 [  0 255 255 255   0]
 [  0 255 255 255   0]]


In [45]:
img=cv2.imread('image1.jpg',0)
r,dst=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
# print(dst.shape)
# print(type(dst))
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
thresh=127
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        px=img[i,j]
        if px< thresh :
            dst[i,j]=255
        else:
            dst[i,j]=0
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 截断阈值处理

In [19]:
img=np.random.randint(0,256,size=(4,5),dtype=np.uint8)
t,rst=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)
print('img=\n',img)
print('t=',t)
print('rst=\n',rst)

img=
 [[237  31 224 126  38]
 [ 58 215  20 134  89]
 [  6  16 155 240  12]
 [126 171  88  69  24]]
t= 127.0
rst=
 [[127  31 127 126  38]
 [ 58 127  20 127  89]
 [  6  16 127 127  12]
 [126 127  88  69  24]]


In [53]:
img=cv2.imread('image1.jpg',0)
r,dst=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)
# print(dst.shape)
# print(type(dst))
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
thresh=127
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        px=img[i,j]
        if px>thresh :
            dst[i,j]=thresh
        else:
            dst[i,j]=0
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


# 超阈值零处理

In [22]:
img=np.random.randint(0,256,size=(4,5),dtype=np.uint8)
t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)
print('img=\n',img)
print('t=',t)
print('rst=\n',rst)

img=
 [[  8 150  86   5  26]
 [ 53 170 143  83  87]
 [ 25 199 159  46  89]
 [178 102   4 121 123]]
t= 127.0
rst=
 [[  8   0  86   5  26]
 [ 53   0   0  83  87]
 [ 25   0   0  46  89]
 [  0 102   4 121 123]]


In [63]:
img=cv2.imread('image1.jpg',0)
r,dst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)
# print(dst.shape)
# print(type(dst))
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
thresh=127
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        px=img[i,j]
        if px>thresh :
            dst[i,j]=0
        else:
            dst[i,j]=px
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 低阈值零处理

In [24]:
img=np.random.randint(0,256,size=(4,5),dtype=np.uint8)
t,rst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO)
print('img=\n',img)
print('t=',t)
print('rst=\n',rst)

img=
 [[151 116 142 126  67]
 [ 73 247 104  11 104]
 [ 66 224 220 240  80]
 [236  93 163  72  89]]
t= 127.0
rst=
 [[151   0 142   0   0]
 [  0 247   0   0   0]
 [  0 224 220 240   0]
 [236   0 163   0   0]]


In [68]:
img=cv2.imread('image1.jpg',0)
r,dst=cv2.threshold(img,127,255,cv2.THRESH_TOZERO)
# print(dst.shape)
# print(type(dst))
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [59]:
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
thresh=127
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        px=img[i,j]
        if px>thresh :
            dst[i,j]=px
        else:
            dst[i,j]=0
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 自适应阈值处理

In [64]:
#对每一个像素点，用它周围的临近区域内像素的加权（均值，高斯均值）平均值，作为阈值
#加权（均值，高斯均值）

In [85]:
img=cv2.imread('image1.jpg',0)
t,thd=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
dst1=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,5,3)
dst2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5,3)
cv2.imshow('img',img)
cv2.imshow('thd',thd)
cv2.imshow('dst1',dst1)
cv2.imshow('dst2',dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [84]:
#均值阈值处理
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
dst=np.zeros(imgInfo,np.uint8)
for i in range(height):
    for j in range(width):
        sum = int(0)
        for m in range(-2,3):# -2 -1 0 1 2
            for n in range(-2,3):
                # 处理越界
                if i + m >= height or i + m < 0:
                    m = -m
                if j + n >= width or j + n < 0:
                    n = -n
                px= img[i+m,j+n]
                sum=sum+px
        thresh=(sum/25)
        if img[i,j]>thresh :
               dst[i,j]=255
        else:
               dst[i,j]=0
cv2.imshow('dst',dst)
cv2.imshow('imae',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [83]:
#高斯滤波阈值处理
hx=np.array([[0.05,0.1,0.05],
           [0.1,0.4,0.1],
           [0.05,0.1,0.05]])
img=cv2.imread('image1.jpg',1)
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
dst=np.zeros(imgInfo,np.uint8)
for i in range(1,height-1):
    for j in range(1,width-1):
        sum = int(0)
        for m in range(-2,3):# -2 -1 0 1 2
            for n in range(-2,3):
                # 处理越界
                if i + m >= height or i + m < 0:
                    m = -m
                if j + n >= width or j + n < 0:
                    n = -n
                px= img[i+m,j+n]
                hb_x=px*hx
                for ii in range(3):
                    for jj in range(3):
                        sum=sum+hb_x[ii,jj]
                thresh=sum
                
                if img[i,j]>thresh :
                       dst[i,j]=255
                else:
                       dst[i,j]=0
cv2.imshow('dst',dst)
cv2.imshow('imae',img)
cv2.waitKey(0)
cv2.destroyAllWindows()