In [1]:
import cv2
import numpy as np

# 腐蚀

In [2]:
img=np.zeros((5,5),np.uint8)
img[1:4,1:4]=1
kernel=np.ones((3,1),np.uint8)
erosion=cv2.erode(img,kernel)
print('img=\n',img)
print('kernel=\n',kernel)
print('erosion=\n',erosion)

img=
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
kernel=
 [[1]
 [1]
 [1]]
erosion=
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [19]:
img=cv2.imread('img2.jpg',cv2.IMREAD_UNCHANGED)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel)
cv2.imshow("img",img)
cv2.imshow("erosion",erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 膨胀

In [20]:
img=cv2.imread("img2.jpg",cv2.IMREAD_UNCHANGED)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.dilate(img,kernel,iterations=2)
cv2.imshow("img",img)
cv2.imshow("erosion",erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img=cv2.imread("img1.png",cv2.IMREAD_UNCHANGED)
dst=cv2.resize(img,None,fx=2,fy=2,interpolation=cv2.INTER_CUBIC)
cv2.imwrite('img2.jpg',dst)

True