In [190]:
import cv2
import numpy as np

In [191]:
# 读取照片并显示
image=cv2.imread('image.jpg')
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [192]:
img = cv2.resize(image,None,fx=0.5,fy=0.5)
rows,cols,channels = img.shape
print(rows,cols,channels)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

352 235 3


In [193]:
print(img[30,30])

[ 16   0 178]


In [194]:
color=int(0)
(b,g,r)=img[30,30]
if b>g and b>r :
    lower= np.array([90,70,70])# 蓝色
    upper= np.array([110,255,255])
    color=(0,0,255)
else:
    lower= np.array([100,200,135])#下限      
    upper= np.array([200,255,245])#上限
    color=(255,0,0)

In [195]:
print(lower,upper)

[100 200 135] [200 255 245]


In [196]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv',hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [197]:
print(hsv[1,2])

[177 254 178]


In [198]:
# 图片的二值化处理
#红底变蓝底
#将在两个阈值内的像素值设置为白色（255），而不在阈值区间内的像素值设置为黑色（0）
# lower= np.array([90,70,70])
# upper= np.array([110,255,255])
# lower_red= np.array([0,120,135])#下限
# upper_red = np.array([200,255,255])#上限
mask = cv2.inRange(hsv, lower, upper)
# 显示图像
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [199]:
#腐蚀膨胀
erode=cv2.erode(mask,None,iterations=1)
cv2.imshow('erode',erode)

dilate=cv2.dilate(erode,None,iterations=2)
cv2.imshow('dilate',dilate)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [200]:
#遍历每个像素点，进行颜色的替换
for i in range(rows):
    for j in range(cols):
        if dilate[i,j]==255: # 像素点为255表示的是白色，我们就是要将白色处的像素点，替换为红色
            img[i,j]=color# 此处替换颜色，为BGR通道，不是RGB通道
cv2.imshow('res',img)
# 窗口等待的命令，0表示无限等待
cv2.waitKey(0)
cv2.destroyAllWindows()

In [153]:
# 读取照片并显示
image=cv2.imread('img1.jpg')
cv2.imshow('image',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
img = cv2.resize(image,None,fx=0.5,fy=0.5)
rows,cols,channels = img.shape
print(rows,cols,channels)
cv2.imshow('img',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
color=int(0)
(b,g,r)=img[30,30]
if b>g and b>r :
    lower= np.array([90,70,70])# 蓝色
    upper= np.array([110,255,255])
    color=(0,0,255)
else:
    lower= np.array([100,200,135])#下限      
    upper= np.array([200,255,245])#上限
    color=(255,0,0)
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv',hsv)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# 图片的二值化处理
#红底变蓝底
#将在两个阈值内的像素值设置为白色（255），而不在阈值区间内的像素值设置为黑色（0）
# lower= np.array([90,70,70])
# upper= np.array([110,255,255])
# lower_red= np.array([0,120,135])#下限
# upper_red = np.array([200,255,255])#上限
mask = cv2.inRange(hsv, lower, upper)
# 显示图像
cv2.imshow('mask',mask)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
#腐蚀膨胀
erode=cv2.erode(mask,None,iterations=1)
cv2.imshow('erode',erode)

dilate=cv2.dilate(erode,None,iterations=1)
cv2.imshow('dilate',dilate)

# cv2.waitKey(0)
# # cv2.destroyAllWindows()
#遍历每个像素点，进行颜色的替换
for i in range(rows):
    for j in range(cols):
        if dilate[i,j]==255: # 像素点为255表示的是白色，我们就是要将白色处的像素点，替换为红色
            img[i,j]=color# 此处替换颜色，为BGR通道，不是RGB通道
cv2.imshow('res',img)
# 窗口等待的命令，0表示无限等待
cv2.waitKey(0)
cv2.destroyAllWindows()

242 172 3


In [218]:
# 读取照片并显示
image=cv2.imread('baidi.jpg')
cv2.imshow('image',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
img = cv2.resize(image,None,fx=0.5,fy=0.5)
rows,cols,channels = img.shape
print(rows,cols,channels)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

262 250 3


In [219]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv',hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [220]:
print(hsv[30,30])

[  0   0 255]


In [221]:
lower= np.array([0,0,221])
upper= np.array([180,10,255])
mask = cv2.inRange(hsv, lower, upper)
# 显示图像
cv2.imshow('mask',mask)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
#腐蚀膨胀
dilate=cv2.dilate(mask,None,iterations=2)
cv2.imshow('dilate',dilate)

erode=cv2.erode(dilate,None,iterations=1)
cv2.imshow('erode',erode)



# cv2.waitKey(0)
# # cv2.destroyAllWindows()
#遍历每个像素点，进行颜色的替换
for i in range(rows):
    for j in range(cols):
        if erode[i,j]==255: # 像素点为255表示的是白色，我们就是要将白色处的像素点，替换为红色
            img[i,j]=(255,255,0)# 此处替换颜色，为BGR通道，不是RGB通道
cv2.imshow('res',img)
# 窗口等待的命令，0表示无限等待
cv2.waitKey(0)
cv2.destroyAllWindows()