In [169]:
import cv2
import numpy as np

In [170]:
# 读取照片并显示
image=cv2.imread('img1.jpg')
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [171]:
img = cv2.resize(image,None,fx=0.5,fy=0.5)
rows,cols,channels = img.shape
print(rows,cols,channels)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

242 172 3


In [172]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv',hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [173]:
hsv_s=hsv[10:20,10:20]
cv2.imshow('hsv_s',hsv_s)
cv2.imshow('hsv',hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [174]:
print(len(hsv_s[0]))

10


In [175]:
print(hsv_s)

[[[102 254 189]
  [102 254 189]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 254 189]]

 [[102 254 189]
  [102 254 189]
  [102 254 189]
  [102 252 190]
  [102 252 190]
  [102 251 191]
  [102 252 190]
  [102 252 190]
  [102 252 190]
  [102 252 190]]

 [[102 254 190]
  [102 254 190]
  [102 252 191]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]]

 [[102 252 191]
  [102 252 191]
  [102 252 191]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]]

 [[102 252 191]
  [102 252 191]
  [102 252 191]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]]

 [[102 252 191]
  [102 252 191]
  [102 252 191]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]
  [102 254 190]]

 [[102 252 191]
  [102 252 1

In [176]:
print(hsv_s[9,9,0])

102


In [177]:
b=int(0)
g=int(0)
r=int(0)
color=int(0)
s=0
#求和
for i in range(len(hsv_s)):
    for j in range(len(hsv_s)):
        b=b+hsv_s[i,j,0]
        g=g+hsv_s[i,j,1]
        r=r+hsv_s[i,j,2]
#平均值
b=int(b/100)
g=int(g/100)
r=int(r/100)
print(b,g,r)


102 252 190


In [178]:
lower= np.array([b-20,g-100,r-120])
upper= np.array([b+10,g+100,r+100])
print(lower)

[ 82 152  70]


In [179]:
mask = cv2.inRange(hsv, lower, upper)
# 显示图像
cv2.imshow('mask',mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [180]:
#腐蚀膨胀
dilate=cv2.dilate(mask,None,iterations=2)
cv2.imshow('dilate',dilate)

erode=cv2.erode(dilate,None,iterations=1)
cv2.imshow('erode',erode)

#遍历每个像素点，进行颜色的替换
for i in range(rows):
    for j in range(cols):
        if erode[i,j]==255: # 像素点为255表示的是白色，我们就是要将白色处的像素点，替换为红色
            img[i,j]=(0,255,255)# 此处替换颜色，为BGR通道，不是RGB通道
cv2.imshow('res',img)
# 窗口等待的命令，0表示无限等待
cv2.waitKey(0)
cv2.destroyAllWindows()