In [1]:
import cv2
import numpy as np

In [12]:
data=np.array([[1],[2],[3]])
print(data)

[[1]
 [2]
 [3]]


In [19]:
data=np.zeros((5,4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
data=np.array([[1,2,3,4],
              [6,7,8,9,10],
              [1,2,4,5,3],
              [6,7,8,9,10]])
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  4,  5,  3],
       [ 6,  7,  8,  9, 10]])

In [20]:
data=np.ones((6,7))
data

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [25]:
data=np.array([[1,2,3],
             [4,5,6]])
data[1,1]=9
data

array([[1, 2, 3],
       [4, 9, 6]])

In [26]:
data[1,2]

6

In [28]:
data/2

array([[0.5, 1. , 1.5],
       [2. , 4.5, 3. ]])

In [35]:
data2=data+5
print(data2)

[[ 6  7  8]
 [ 9 14 11]]


In [36]:
data1=data-4
print(data1)

[[-3 -2 -1]
 [ 0  5  2]]


In [37]:
data1+data2

array([[ 3,  5,  7],
       [ 9, 19, 13]])

In [38]:
data1-data2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [39]:
data1*data2

array([[-18, -14,  -8],
       [  0,  70,  22]])

In [40]:
data/data2

array([[0.16666667, 0.28571429, 0.375     ],
       [0.44444444, 0.64285714, 0.54545455]])