In [2]:
#边缘算子
#1.canny 算子 2. sobel算子 3.robert 算子
#4.拉普拉斯算子  5. marr算子
#sobel算子 横向和竖向
#横向 

In [3]:
import numpy as np
import cv2
import math

In [4]:
hx=np.array([[1,2,1],
           [0,0,0],
           [-1,-2,-1]])
print(hx)
hy=np.array([[1,0,-1],
            [2,0,-2],
            [1,0,-1]])
for i in range(3):
    for j in range(3):
        print (hx[i,j])

[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]
1
2
1
0
0
0
-1
-2
-1


In [6]:
#sobel算子
img=cv2.imread('img2.jpg',0)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
dst=np.zeros(imgInfo,np.uint8)
for i in range(1,height-1):
    for j in range(1,width-1):
        gx=img[i-1:i+2,j-1:j+2]*hx
        gy=img[i-1:i+2,j-1:j+2]*hy
        gxs=0
        gys=0
        for ii in range(3):
            for jj in range(3):
                gxs=gxs+gx[ii,jj]
                gys=gys+gy[ii,jj]
        th=math.sqrt(gxs*gxs+gys*gys)
        if th>150 :
            dst[i,j]=255
        else:
            dst[i,j]=0
cv2.imshow('dst',dst)
cv2.imshow('imae',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
img.shape

(291, 512)

In [30]:
img.shape

(291, 512)

In [35]:
cv2.imshow('img',img[1-1:1+1,1-1:1+1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
img[1-1:1+1,1-1:1+1].shape

(2, 2)

In [15]:
#canny 算子
img=cv2.imread('img2.jpg',0)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
dst=np.zeros(imgInfo,np.uint8)
imgG=cv2.GaussianBlur(img,(3,3),0)#高斯滤波
dst=cv2.Canny(imgG,50,50)#src 2 th1 3 th2
cv2.imshow('dst',dst)
cv2.imshow('imae',img)
cv2.waitKey(0)
cv2.destroyAllWindows()