In [1]:
#采用类似边缘检测的方法
#对紧邻的像素做差，newp=gray0-gray1+150
#newP
import numpy as np
import cv2

In [32]:
#sobel算子
img=cv2.imread('img2.jpg',0)
imgInfo = img.shape
height = imgInfo[0]
width = imgInfo[1]
dst=np.zeros(imgInfo,np.uint8)
for i in range(height-1):
    for j in range(width):
        newp=0
        newp=int(img[i,j]-img[i+1,j]+150)
        if newp>255:
            dst[i,j]=255
        elif newp<0:
            dst[i,j]=0
        else:
            dst[i,j]=newp
for i in range(height-1,height):
    for j in range(width):
        dst[i,j]=255
cv2.imshow('dst',dst)
cv2.imshow('imae',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

C:\py\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in ubyte_scalars
  # Remove the CWD from sys.path while we load stuff.


In [7]:
img[0,0]-img[0,1]+150

150

In [21]:
print(img)

[[168 158 162 ... 138 141 139]
 [161 157 157 ... 134 136 140]
 [154 153 153 ... 131 135 143]
 ...
 [179 172 173 ... 179 178 179]
 [169 164 165 ... 176 175 174]
 [159 156 158 ... 178 177 175]]


In [23]:
print(img[1,2])

157
